"""OntoBridge - end-to-end pipeline demo.

Demonstrates the full pipeline from raw text to published SKOS/OWL terms.
Runs without any external services - everything stays in memory.

Usage
-----
    python examples/demo.py
    python examples/demo.py --output results/

Output written to --output (default: examples/output/):
    glossary.csv   - published terms as a spreadsheet
    glossary.ttl   - SKOS/OWL Turtle for import into Protégé / GraphDB
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

# Make sure the package is importable from the repo root
_SRC = Path(__file__).resolve().parents[1] / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from ontobridge.agents.governance.ontology import OntologyIndex
from ontobridge.batch import BatchPipelineRunner
from ontobridge.export import export_glossary_csv, export_turtle
from ontobridge.models import CandidateLabel, EnrichedTerm, LifecycleStatus
from ontobridge.models.enums import SourceType
from ontobridge.models.source import HarvestRecord, SourceRef
from ontobridge.pipeline import PipelineRunner
from ontobridge.publisher import InMemoryPublisher

_ONTOLOGY = Path(__file__).resolve().parents[1] / "ontology" / "ontobridge_ontology_v0.1.ttl"
_SAMPLE_DOC = Path(__file__).resolve().parent / "sample_policy.txt"

_SEP = "-" * 60


def _header(title: str) -> None:
    print(f"\n{_SEP}")
    print(f"  {title}")
    print(_SEP)


def _ok(msg: str) -> None:
    print(f"  [OK] {msg}")


def _info(msg: str) -> None:
    print(f"       {msg}")


# ---------------------------------------------------------------------------
# Step 1 - load ontology
# ---------------------------------------------------------------------------

def step_load_ontology() -> OntologyIndex:
    _header("Step 1 - Load ontology")
    t0 = time.perf_counter()
    ontology = OntologyIndex.from_file(_ONTOLOGY)
    elapsed = time.perf_counter() - t0
    scheme_labels = list(ontology._scheme_labels.values())
    _ok(f"Loaded in {elapsed:.2f}s - {len(scheme_labels)} SKOS scheme(s)")
    for label in sorted(scheme_labels):
        _info(label)
    return ontology


# ---------------------------------------------------------------------------
# Step 2 - run a single term manually
# ---------------------------------------------------------------------------

def step_single_term(ontology: OntologyIndex, publisher: InMemoryPublisher) -> None:
    _header("Step 2 - Single term via PipelineRunner")

    record = HarvestRecord(
        text=(
            "Net interest margin is the difference between the interest income "
            "generated by a bank and the interest paid to depositors, expressed "
            "as a percentage of interest-earning assets."
        ),
        source_type=SourceType.POLICY_DOC,
        source_ref=SourceRef(source_system="demo", document_id="CreditPolicy_v3.pdf"),
    )
    term = EnrichedTerm(
        harvest_record=record,
        candidate_labels=[CandidateLabel(text="Net interest margin", confidence=1.0)],
        definition=record.text,
    )

    runner = PipelineRunner(ontology, publisher)
    t0 = time.perf_counter()
    published = runner.run(term)
    elapsed = time.perf_counter() - t0

    gov = published.enriched_term.governance_result
    placement = published.enriched_term.taxonomy_placement

    _ok(f"'{published.enriched_term.preferred_label}' published in {elapsed:.3f}s")
    _info(f"URI:        {published.term_uri}")
    _info(f"Status:     {published.lifecycle_status.value}")
    if placement:
        _info(f"Scheme:     {placement.scheme_uri}")
        _info(f"Parent:     {placement.broader_concept_uri}")
    if gov:
        _info(f"Governance: {gov.recommended_action} "
              f"(flags: {', '.join(gov.blocking_flags) or 'none'})")


# ---------------------------------------------------------------------------
# Step 3 - batch run from document
# ---------------------------------------------------------------------------

def step_batch_document(ontology: OntologyIndex, publisher: InMemoryPublisher) -> None:
    _header("Step 3 - Batch run from sample_policy.txt")

    if not _SAMPLE_DOC.exists():
        print("  [SKIP] sample_policy.txt not found - skipping batch step")
        return

    progress_log: list[str] = []

    def on_progress(done: int, total: int) -> None:
        progress_log.append(f"{done}/{total}")

    batch = BatchPipelineRunner(ontology, publisher, on_progress=on_progress)
    t0 = time.perf_counter()
    result = batch.run_document(_SAMPLE_DOC, source_system="retail_credit_policy")
    elapsed = time.perf_counter() - t0

    _ok(f"Finished in {elapsed:.2f}s - {result.summary()}")
    _info(f"Progress ticks: {' -> '.join(progress_log)}")

    if result.published:
        _info("")
        _info("Published terms:")
        for pt in sorted(result.published, key=lambda t: t.enriched_term.preferred_label or ""):
            gov = pt.enriched_term.governance_result
            action = gov.recommended_action if gov else "-"
            _info(f"  * {pt.enriched_term.preferred_label:<30} [{action}]")

    if result.skipped:
        _info("")
        _info(f"Skipped ({len(result.skipped)}):")
        for term, reason in result.skipped:
            _info(f"  * {term.preferred_label or '?'} - {reason[:60]}")

    if result.failed:
        _info("")
        _info(f"Failed ({len(result.failed)}):")
        for ft in result.failed:
            _info(f"  * {ft.term.preferred_label or '?'} - {ft.error[:60]}")


# ---------------------------------------------------------------------------
# Step 4 - export
# ---------------------------------------------------------------------------

def step_export(publisher: InMemoryPublisher, output_dir: Path) -> None:
    _header("Step 4 - Export results")

    output_dir.mkdir(parents=True, exist_ok=True)

    csv_path = output_dir / "glossary.csv"
    ttl_path = output_dir / "glossary.ttl"

    # Export all statuses in the demo (real use: only PUBLISHED)
    from ontobridge.models.enums import LifecycleStatus as LS
    all_statuses = set(LS)
    csv_text = export_glossary_csv(publisher, statuses=all_statuses)
    csv_path.write_text(csv_text, encoding="utf-8")
    rows = len(csv_text.strip().splitlines()) - 1  # minus header
    _ok(f"CSV  -> {csv_path}  ({rows} term rows, all statuses)")

    ttl_text = export_turtle(publisher, statuses=all_statuses, output_path=ttl_path)
    _ok(f"TTL  -> {ttl_path}  ({len(ttl_text.splitlines())} lines)")

    _info("")
    _info("Open glossary.ttl in Protege or GraphDB to explore the ontology.")
    _info("Open glossary.csv in Excel or Google Sheets for a human-readable view.")


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

def step_summary(publisher: InMemoryPublisher) -> None:
    _header("Summary")
    terms = publisher.search_terms("")
    from collections import Counter
    counts = Counter(t.lifecycle_status.value for t in terms)
    _ok(f"Total terms in publisher: {len(terms)}")
    for status, n in sorted(counts.items()):
        _info(f"  {status:<12} {n}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="OntoBridge pipeline demo")
    parser.add_argument(
        "--output",
        default=str(Path(__file__).parent / "output"),
        help="Directory for exported files (default: examples/output/)",
    )
    args = parser.parse_args()

    print("\nOntoBridge - Pipeline Demo")
    print("=" * 60)

    publisher = InMemoryPublisher()
    ontology = step_load_ontology()
    step_single_term(ontology, publisher)
    step_batch_document(ontology, publisher)
    step_export(publisher, Path(args.output))
    step_summary(publisher)

    print(f"\n{'=' * 60}")
    print("  Demo complete.")
    print(f"{'=' * 60}\n")


if __name__ == "__main__":
    main()
