from __future__ import annotations

from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import DCTERMS, OWL, RDF, RDFS, SKOS

from ontobridge.agents.governance.ontology import OntologyIndex
from ontobridge.agents.taxonomy import camelcase_label
from ontobridge.models.enrichment import EnrichedTerm
from ontobridge.models.enums import RelationStatus
from ontobridge.models.published import PublishedTerm
from ontobridge.publisher.base import TermPublisher

DEFAULT_BANK_NAMESPACE = "http://ontobridge.dev/ontology/bank/"
DEFAULT_REL_NAMESPACE = "http://ontobridge.dev/ontology/bank/relations/"
_LANG = "en"


class WriterAgent:
    def __init__(
        self,
        publisher: TermPublisher,
        ontology: OntologyIndex | None = None,
        bank_namespace: str = DEFAULT_BANK_NAMESPACE,
        rel_namespace: str = DEFAULT_REL_NAMESPACE,
    ):
        self.publisher = publisher
        self.ontology = ontology
        self.bank_namespace = bank_namespace
        self.rel_namespace = rel_namespace
        self._label_to_uri: dict[str, str] = (
            self._build_label_index(ontology) if ontology else {}
        )

    @staticmethod
    def _build_label_index(ontology: OntologyIndex) -> dict[str, str]:
        idx: dict[str, str] = {}
        for c in ontology.concepts:
            idx[c.pref_label.casefold()] = c.uri
            for alt in c.alt_labels:
                idx.setdefault(alt.casefold(), c.uri)
        return idx

    # ---------------- public API ----------------

    def assemble(
        self,
        term: EnrichedTerm,
        term_uri: str | None = None,
        approved_by: str | None = None,
    ) -> PublishedTerm:
        if term_uri is None:
            term_uri = self._derive_uri(term)
        published = PublishedTerm.from_enriched(
            term, term_uri=term_uri, approved_by=approved_by
        )
        published.turtle = self.to_turtle(published)
        return published

    def publish(
        self,
        term: EnrichedTerm,
        term_uri: str | None = None,
        approved_by: str | None = None,
    ) -> PublishedTerm:
        published = self.assemble(term, term_uri=term_uri, approved_by=approved_by)
        self.publisher.create_term(published)
        return published

    # ---------------- Turtle serialization ----------------

    def to_turtle(self, published: PublishedTerm) -> str:
        g = Graph()
        bank = Namespace(self.bank_namespace)
        bank_rel = Namespace(self.rel_namespace)
        g.bind("skos", SKOS)
        g.bind("owl", OWL)
        g.bind("rdfs", RDFS)
        g.bind("dct", DCTERMS)
        g.bind("bank", bank)
        g.bind("bank-rel", bank_rel)

        enriched = published.enriched_term
        subject = URIRef(published.term_uri)

        g.add((subject, RDF.type, SKOS.Concept))
        self._emit_labels(g, subject, enriched)
        self._emit_definition(g, subject, enriched)
        self._emit_taxonomy(g, subject, enriched)
        self._emit_fibo(g, subject, enriched)
        self._emit_relations(g, subject, enriched)
        self._emit_provenance(g, subject, enriched)
        g.add((
            subject,
            SKOS.editorialNote,
            Literal("Generated by OntoBridge pipeline", lang=_LANG),
        ))
        return g.serialize(format="turtle")

    @staticmethod
    def _emit_labels(g: Graph, subject: URIRef, enriched: EnrichedTerm) -> None:
        if enriched.preferred_label:
            g.add((subject, SKOS.prefLabel, Literal(enriched.preferred_label, lang=_LANG)))
        seen: set[str] = (
            {enriched.preferred_label.casefold()} if enriched.preferred_label else set()
        )
        for cand in enriched.candidate_labels:
            key = cand.text.casefold()
            if key in seen:
                continue
            g.add((subject, SKOS.altLabel, Literal(cand.text, lang=_LANG)))
            seen.add(key)

    @staticmethod
    def _emit_definition(g: Graph, subject: URIRef, enriched: EnrichedTerm) -> None:
        if enriched.definition:
            g.add((subject, SKOS.definition, Literal(enriched.definition, lang=_LANG)))

    @staticmethod
    def _emit_taxonomy(g: Graph, subject: URIRef, enriched: EnrichedTerm) -> None:
        placement = enriched.taxonomy_placement
        if placement is None:
            return
        if placement.broader_concept_uri:
            g.add((subject, SKOS.broader, URIRef(placement.broader_concept_uri)))
        if placement.scheme_uri:
            g.add((subject, SKOS.inScheme, URIRef(placement.scheme_uri)))

    @staticmethod
    def _emit_fibo(g: Graph, subject: URIRef, enriched: EnrichedTerm) -> None:
        if enriched.fibo_match and enriched.fibo_match.uri:
            g.add((subject, SKOS.exactMatch, URIRef(enriched.fibo_match.uri)))

    def _emit_relations(self, g: Graph, subject: URIRef, enriched: EnrichedTerm) -> None:
        for rel in enriched.relations:
            if rel.status is not RelationStatus.RESOLVED:
                continue
            if not rel.predicate_uri:
                continue
            obj_term = self._resolve_object(rel.object_label)
            g.add((subject, URIRef(rel.predicate_uri), obj_term))
            # Emit the inverse as a forward triple from object → subject only when
            # the object resolved to a URI; with a literal object, the inverse is
            # implicit via owl:inverseOf on the property declaration.
            if isinstance(obj_term, URIRef) and rel.inverse_predicate_uri:
                g.add((obj_term, URIRef(rel.inverse_predicate_uri), subject))

    @staticmethod
    def _emit_provenance(g: Graph, subject: URIRef, enriched: EnrichedTerm) -> None:
        for ctx in enriched.policy_context:
            if not ctx.document_ref:
                continue
            ref = f"policy:{ctx.document_ref}"
            if ctx.section:
                ref += f"#section-{ctx.section}"
            g.add((subject, DCTERMS.source, URIRef(ref)))

    def _resolve_object(self, label: str) -> URIRef | Literal:
        uri = self._label_to_uri.get(label.casefold())
        if uri is not None:
            return URIRef(uri)
        return Literal(label, lang=_LANG)

    # ---------------- URI derivation ----------------

    def _derive_uri(self, term: EnrichedTerm) -> str:
        placement = term.taxonomy_placement
        if placement is not None and placement.domain_prefix:
            curie = placement.domain_prefix
            if ":" in curie:
                _, suffix = curie.split(":", 1)
                if suffix:
                    return f"{self.bank_namespace}{suffix}"
        label = term.preferred_label or "Unknown"
        return f"{self.bank_namespace}{camelcase_label(label)}"
